pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    upstream angular-app {
        server frontend:4200;
    }

    upstream produto-service {
        server produto_service:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://angular-app;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/produtos/ {
            proxy_pass http://produto-service/;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Prefix /api/produtos;
        }
    }
}