CREATE TABLE IF NOT EXISTS CATEGORIA(
    ID_CATEGORIA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NM_CATEGORIA VARCHAR(50) NOT NULL,
    NM_SLUG_CATEGORIA VARCHAR(100) NOT NULL UNIQUE,
    ID_CATEGORIA_PAI BIGINT,
    DT_DATA_CRIACAO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DT_DATA_ULTIMA_ALTERACAO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_CATEGORIA_PAI FOREIGN KEY (ID_CATEGORIA_PAI) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
    ID_PRODUTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NM_PRODUTO VARCHAR(150) NOT NULL,
    NM_SLUG_PRODUTO VARCHAR(250) NOT NULL UNIQUE,
    NM_DESCRICAO VARCHAR(500) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    QTD_ESTOQUE INT NOT NULL,
    IN_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    ID_CATEGORIA BIGINT NOT NULL,
    DT_DATA_CRIACAO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DT_DATA_ULTIMA_ALTERACAO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS AVALIACAO(
    ID_AVALIACAO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PRODUTO BIGINT NOT NULL,
    ID_USUARIO BIGINT NOT NULL,
    QT_NOTA INT NOT NULL CHECK (QT_NOTA >= 1 AND QT_NOTA <= 5),
    DS_COMENTARIO VARCHAR(500),
    DT_DATA_CRIACAO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DT_DATA_ULTIMA_ALTERACAO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUTO_FOTO(
    ID_PRODUTO_FOTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DS_URL VARCHAR(500) NOT NULL,
    IN_PRINCIPAL BOOLEAN NOT NULL DEFAULT FALSE,
    ID_PRODUTO BIGINT NOT NULL,
    DT_DATA_CRIACAO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DT_DATA_ULTIMA_ALTERACAO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO) ON DELETE CASCADE
);

